# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml
  pundit: config/rubocop-rspec.yml
  rubocop-rspec: config/default.yml
  rubocop-rspec_rails: config/default.yml
  rubocop-capybara: config/default.yml
  rubocop-faker: config/default.yml
  rubocop-factory_bot: config/default.yml

require:
  - rubocop-faker
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
    NewCops: enable
